import { useMemo, useState } from 'react';
import { BadgeCheck, CircleAlert, MapPin, Search, ShieldCheck, Star, Truck, UserRoundSearch, Users } from 'lucide-react';

import { Language } from '../../types';
import { cn } from '../../lib/cn';
import { Card } from '../ui/Card';

type DriverState = 'Driving' | 'Available' | 'Off duty' | 'Compliance hold';
const DRIVERS = [
  { id: 'DRV-2048', name: 'Marco Petrovic', company: 'Adria Freight d.o.o.', country: 'BA', vehicle: 'PT-19', load: 'SF-9082', location: 'Vienna, AT', rating: 4.9, trips: 342, state: 'Driving' as DriverState },
  { id: 'DRV-1994', name: 'Lena Weber', company: 'Nord Cargo GmbH', country: 'DE', vehicle: 'DE-442', load: 'SF-9077', location: 'Munich, DE', rating: 4.8, trips: 291, state: 'Driving' as DriverState },
  { id: 'DRV-1881', name: 'Amir Hadzic', company: 'Adria Freight d.o.o.', country: 'BA', vehicle: 'BA-908', load: '—', location: 'Zagreb, HR', rating: 4.9, trips: 274, state: 'Available' as DriverState },
  { id: 'DRV-1742', name: 'Pieter Vos', company: 'Benelux Transport BV', country: 'NL', vehicle: 'NL-771', load: '—', location: 'Rotterdam, NL', rating: 4.7, trips: 238, state: 'Off duty' as DriverState },
  { id: 'DRV-1610', name: 'Tomasz Nowak', company: 'Baltic Route Sp. z o.o.', country: 'PL', vehicle: 'PL-304', load: '—', location: 'Warsaw, PL', rating: 4.6, trips: 201, state: 'Compliance hold' as DriverState },
];
const tones: Record<DriverState, string> = { Driving: 'bg-sky-500/10 text-sky-600', Available: 'bg-emerald-500/10 text-emerald-600', 'Off duty': 'bg-slate-500/10 text-slate-600', 'Compliance hold': 'bg-rose-500/10 text-rose-600' };

export const AdminDriversView = ({ lang: _lang }: { lang: Language }) => {
  const [query, setQuery] = useState('');
  const [state, setState] = useState<'All' | DriverState>('All');
  const visible = useMemo(() => DRIVERS.filter((driver) => `${driver.name} ${driver.company} ${driver.id} ${driver.location}`.toLowerCase().includes(query.toLowerCase()) && (state === 'All' || driver.state === state)), [query, state]);
  return <div className="space-y-6">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-500/10 text-sky-500"><UserRoundSearch className="h-6 w-6" /></div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-primary">Global workforce</p><h1 className="text-2xl font-black dark:text-white">All Drivers</h1></div></div><p className="mt-4 text-sm text-slate-500">Track every driver across companies, current assignments, location, compliance, performance, and availability.</p></section>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card className="p-4"><p className="text-xs uppercase text-slate-500">Verified drivers</p><p className="mt-1 text-3xl font-black dark:text-white">3,842</p></Card><Card className="p-4"><p className="text-xs uppercase text-slate-500">Driving now</p><p className="mt-1 text-3xl font-black text-sky-500">1,284</p></Card><Card className="p-4"><p className="text-xs uppercase text-slate-500">Available</p><p className="mt-1 text-3xl font-black text-emerald-500">612</p></Card><Card className="p-4"><p className="text-xs uppercase text-slate-500">Compliance holds</p><p className="mt-1 text-3xl font-black text-rose-500">14</p></Card></div>
    <Card><div className="flex flex-wrap items-center justify-between gap-4"><div className="relative min-w-64 flex-1 max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search driver, company or location..." className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-primary dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></div><div className="flex flex-wrap gap-2">{(['All', 'Driving', 'Available', 'Off duty', 'Compliance hold'] as const).map((option) => <button key={option} onClick={() => setState(option)} className={cn('rounded-xl px-3 py-2 text-xs font-bold', state === option ? 'bg-primary text-white' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300')}>{option}</button>)}</div></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-500 dark:border-slate-800"><th className="p-3">Driver</th><th className="p-3">Company</th><th className="p-3">Vehicle / load</th><th className="p-3">Live location</th><th className="p-3">Rating</th><th className="p-3">Trips</th><th className="p-3">State</th><th className="p-3">Compliance</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{visible.map((driver) => <tr key={driver.id}><td className="p-3"><p className="font-bold text-slate-900 dark:text-white">{driver.name}</p><p className="text-xs text-slate-500">{driver.id} · {driver.country}</p></td><td className="p-3 text-sm text-slate-600 dark:text-slate-300">{driver.company}</td><td className="p-3"><p className="flex items-center gap-1 text-sm font-semibold dark:text-white"><Truck className="h-3.5 w-3.5 text-primary" />{driver.vehicle}</p><p className="text-xs text-slate-500">Load {driver.load}</p></td><td className="p-3 text-sm text-slate-500"><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{driver.location}</span></td><td className="p-3"><span className="flex items-center gap-1 text-sm font-bold"><Star className="h-4 w-4 fill-amber-400 text-amber-400" />{driver.rating}</span></td><td className="p-3 text-sm">{driver.trips}</td><td className="p-3"><span className={cn('rounded-full px-2 py-1 text-xs font-bold', tones[driver.state])}>{driver.state}</span></td><td className="p-3">{driver.state === 'Compliance hold' ? <CircleAlert className="h-5 w-5 text-rose-500" /> : <BadgeCheck className="h-5 w-5 text-emerald-500" />}</td></tr>)}</tbody></table></div>
    </Card>
    <Card><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" /><p className="font-black dark:text-white">Superadmin driver permissions</p></div><div className="mt-3 flex flex-wrap gap-2">{['View all profiles', 'Track live location', 'Inspect assigned loads', 'Review documents', 'Suspend or verify access', 'Audit status history'].map((item) => <span key={item} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600 dark:border-slate-700 dark:text-slate-300">{item}</span>)}</div></Card>
  </div>;
};
