import { Language } from '../../types';

type Locale = Exclude<Language, null>;

export type CompanyOverviewCopy = {
  company: string;
  title: string;
  subtitle: string;
  live: string;
  assetsSummary: string;
  stats: [string, string, string];
  metrics: [[string, string], [string, string], [string, string], [string, string]];
  dispatch: [string, string, string];
  statuses: [string, string, string];
  health: [string, string, string, string];
  activityTitle: string;
  activities: [[string, string], [string, string], [string, string], [string, string]];
  performance: [string, string, string];
};

const COPY: Record<Locale, CompanyOverviewCopy> = {
  en: {
    company: 'Logistics Company', title: 'Operations Overview', subtitle: 'A live command center for fleet movement, dispatch performance, team activity, and delivery risk.', live: 'Live operations', assetsSummary: '24 assets · 12 active loads',
    stats: ['Revenue today', 'Kilometers active', 'Capacity utilized'],
    metrics: [['Active vehicles', 'of 24 fleet assets'], ['Loads in transit', '4 arriving today'], ['Team online', '7 drivers on duty'], ['On-time performance', '+2.4% this month']],
    dispatch: ['Live dispatch board', 'Priority routes and current execution progress.', '12 active'], statuses: ['Tomorrow', 'In transit', 'Final mile'],
    health: ['Operational health', 'Routes on schedule', 'Delay watch', 'Critical alerts'], activityTitle: 'Recent activity',
    activities: [['Lena assigned load SF-2049 to driver PT-19', '8 min ago'], ['Vehicle DE-442 entered the Munich delivery zone', '21 min ago'], ['Finance approved payout for Nord Cargo GmbH', '42 min ago'], ['Driver invitation accepted by Adnan K.', '1h ago']],
    performance: ['Company performance is trending up', 'On-time delivery improved 2.4% while empty kilometers dropped 8.1% this month.', 'Open analytics'],
  },
  bs: {
    company: 'Logistička kompanija', title: 'Pregled operacija', subtitle: 'Kontrolni centar uživo za kretanje flote, učinak dispečera, aktivnosti tima i rizike isporuke.', live: 'Operacije uživo', assetsSummary: '24 vozila · 12 aktivnih tereta',
    stats: ['Prihod danas', 'Aktivni kilometri', 'Iskorištenost kapaciteta'], metrics: [['Aktivna vozila', 'od 24 vozila u floti'], ['Tereti u tranzitu', '4 stižu danas'], ['Tim online', '7 vozača na dužnosti'], ['Tačnost isporuke', '+2,4% ovog mjeseca']],
    dispatch: ['Dispečerska tabla uživo', 'Prioritetne rute i trenutni napredak realizacije.', '12 aktivnih'], statuses: ['Sutra', 'U tranzitu', 'Završna etapa'], health: ['Operativno stanje', 'Rute po rasporedu', 'Praćenje kašnjenja', 'Kritična upozorenja'], activityTitle: 'Nedavne aktivnosti',
    activities: [['Lena je dodijelila teret SF-2049 vozaču PT-19', 'prije 8 min'], ['Vozilo DE-442 ušlo je u zonu isporuke Minhen', 'prije 21 min'], ['Finansije su odobrile isplatu za Nord Cargo GmbH', 'prije 42 min'], ['Adnan K. je prihvatio poziv za vozača', 'prije 1 h']], performance: ['Učinak kompanije raste', 'Tačnost isporuke poboljšana je za 2,4%, a prazni kilometri smanjeni su za 8,1% ovog mjeseca.', 'Otvori analitiku'],
  },
  de: {
    company: 'Logistikunternehmen', title: 'Betriebsübersicht', subtitle: 'Eine Live-Zentrale für Flottenbewegungen, Disposition, Teamaktivität und Lieferrisiken.', live: 'Live-Betrieb', assetsSummary: '24 Fahrzeuge · 12 aktive Ladungen',
    stats: ['Umsatz heute', 'Aktive Kilometer', 'Kapazitätsauslastung'], metrics: [['Aktive Fahrzeuge', 'von 24 Flottenfahrzeugen'], ['Ladungen unterwegs', '4 kommen heute an'], ['Team online', '7 Fahrer im Einsatz'], ['Pünktlichkeit', '+2,4 % diesen Monat']],
    dispatch: ['Live-Disposition', 'Prioritätsrouten und aktueller Ausführungsfortschritt.', '12 aktiv'], statuses: ['Morgen', 'Unterwegs', 'Letzte Meile'], health: ['Betriebszustand', 'Routen im Zeitplan', 'Verspätungen beobachten', 'Kritische Warnungen'], activityTitle: 'Letzte Aktivitäten',
    activities: [['Lena hat Ladung SF-2049 Fahrer PT-19 zugewiesen', 'vor 8 Min.'], ['Fahrzeug DE-442 erreichte die Münchner Lieferzone', 'vor 21 Min.'], ['Finanzen genehmigte die Auszahlung an Nord Cargo GmbH', 'vor 42 Min.'], ['Fahrereinladung von Adnan K. angenommen', 'vor 1 Std.']], performance: ['Unternehmensleistung steigt', 'Die Pünktlichkeit stieg diesen Monat um 2,4 %, Leerfahrten sanken um 8,1 %.', 'Analysen öffnen'],
  },
  pl: {
    company: 'Firma logistyczna', title: 'Przegląd operacji', subtitle: 'Centrum zarządzania ruchem floty, wydajnością dyspozycji, aktywnością zespołu i ryzykiem dostaw na żywo.', live: 'Operacje na żywo', assetsSummary: '24 pojazdy · 12 aktywnych ładunków',
    stats: ['Dzisiejszy przychód', 'Aktywne kilometry', 'Wykorzystanie ładowności'], metrics: [['Aktywne pojazdy', 'z 24 pojazdów floty'], ['Ładunki w drodze', '4 dotrą dzisiaj'], ['Zespół online', '7 kierowców na służbie'], ['Terminowość', '+2,4% w tym miesiącu']], dispatch: ['Tablica dyspozytorska na żywo', 'Priorytetowe trasy i bieżący postęp realizacji.', '12 aktywnych'], statuses: ['Jutro', 'W transporcie', 'Ostatnia mila'], health: ['Stan operacyjny', 'Trasy zgodnie z planem', 'Monitorowanie opóźnień', 'Krytyczne alerty'], activityTitle: 'Ostatnia aktywność',
    activities: [['Lena przypisała ładunek SF-2049 kierowcy PT-19', '8 min temu'], ['Pojazd DE-442 wjechał do strefy dostaw w Monachium', '21 min temu'], ['Finanse zatwierdziły wypłatę dla Nord Cargo GmbH', '42 min temu'], ['Adnan K. zaakceptował zaproszenie kierowcy', '1 godz. temu']], performance: ['Wyniki firmy rosną', 'Terminowość dostaw wzrosła o 2,4%, a puste kilometry spadły o 8,1% w tym miesiącu.', 'Otwórz analitykę'],
  },
  ro: {
    company: 'Companie logistică', title: 'Prezentare operațională', subtitle: 'Un centru live pentru mișcarea flotei, performanța dispeceratului, activitatea echipei și riscurile livrării.', live: 'Operațiuni live', assetsSummary: '24 vehicule · 12 încărcături active', stats: ['Venit astăzi', 'Kilometri activi', 'Capacitate utilizată'], metrics: [['Vehicule active', 'din 24 vehicule ale flotei'], ['Încărcături în tranzit', '4 sosesc astăzi'], ['Echipă online', '7 șoferi la datorie'], ['Performanță la timp', '+2,4% luna aceasta']], dispatch: ['Panou de dispecerat live', 'Rute prioritare și progresul curent al execuției.', '12 active'], statuses: ['Mâine', 'În tranzit', 'Ultimul kilometru'], health: ['Stare operațională', 'Rute conform programului', 'Monitorizare întârzieri', 'Alerte critice'], activityTitle: 'Activitate recentă', activities: [['Lena a atribuit încărcătura SF-2049 șoferului PT-19', 'acum 8 min'], ['Vehiculul DE-442 a intrat în zona de livrare München', 'acum 21 min'], ['Finanțele au aprobat plata pentru Nord Cargo GmbH', 'acum 42 min'], ['Adnan K. a acceptat invitația de șofer', 'acum 1 h']], performance: ['Performanța companiei este în creștere', 'Livrările la timp au crescut cu 2,4%, iar kilometrii fără marfă au scăzut cu 8,1% luna aceasta.', 'Deschide analizele'],
  },
  nl: {
    company: 'Logistiek bedrijf', title: 'Operationeel overzicht', subtitle: 'Een live commandocentrum voor vlootbewegingen, dispatchprestaties, teamactiviteit en leveringsrisico.', live: 'Live operaties', assetsSummary: '24 voertuigen · 12 actieve ladingen', stats: ['Omzet vandaag', 'Actieve kilometers', 'Benutte capaciteit'], metrics: [['Actieve voertuigen', 'van 24 vlootvoertuigen'], ['Ladingen onderweg', '4 arriveren vandaag'], ['Team online', '7 chauffeurs in dienst'], ['Prestaties op tijd', '+2,4% deze maand']], dispatch: ['Live dispatchbord', 'Prioriteitsroutes en actuele uitvoeringsvoortgang.', '12 actief'], statuses: ['Morgen', 'Onderweg', 'Laatste kilometer'], health: ['Operationele status', 'Routes op schema', 'Vertragingen bewaken', 'Kritieke meldingen'], activityTitle: 'Recente activiteit', activities: [['Lena wees lading SF-2049 toe aan chauffeur PT-19', '8 min geleden'], ['Voertuig DE-442 reed de bezorgzone van München binnen', '21 min geleden'], ['Finance keurde betaling aan Nord Cargo GmbH goed', '42 min geleden'], ['Chauffeursuitnodiging geaccepteerd door Adnan K.', '1 uur geleden']], performance: ['Bedrijfsprestaties stijgen', 'Tijdige levering steeg deze maand met 2,4% en lege kilometers daalden met 8,1%.', 'Analytics openen'],
  },
  fr: {
    company: 'Entreprise logistique', title: 'Vue d’ensemble des opérations', subtitle: 'Un centre de commande en direct pour les mouvements de flotte, la répartition, l’activité de l’équipe et les risques de livraison.', live: 'Opérations en direct', assetsSummary: '24 véhicules · 12 chargements actifs', stats: ['Revenu du jour', 'Kilomètres actifs', 'Capacité utilisée'], metrics: [['Véhicules actifs', 'sur 24 véhicules'], ['Chargements en transit', '4 arrivent aujourd’hui'], ['Équipe en ligne', '7 conducteurs en service'], ['Ponctualité', '+2,4 % ce mois-ci']], dispatch: ['Tableau de répartition en direct', 'Itinéraires prioritaires et progression actuelle.', '12 actifs'], statuses: ['Demain', 'En transit', 'Dernier kilomètre'], health: ['Santé opérationnelle', 'Itinéraires à l’heure', 'Surveillance des retards', 'Alertes critiques'], activityTitle: 'Activité récente', activities: [['Lena a attribué le chargement SF-2049 au conducteur PT-19', 'il y a 8 min'], ['Le véhicule DE-442 est entré dans la zone de livraison de Munich', 'il y a 21 min'], ['La finance a approuvé le paiement de Nord Cargo GmbH', 'il y a 42 min'], ['Invitation conducteur acceptée par Adnan K.', 'il y a 1 h']], performance: ['Les performances de l’entreprise progressent', 'Les livraisons à l’heure ont augmenté de 2,4 % et les kilomètres à vide ont baissé de 8,1 % ce mois-ci.', 'Ouvrir les analyses'],
  },
  it: {
    company: 'Azienda logistica', title: 'Panoramica operativa', subtitle: 'Un centro di comando in tempo reale per flotta, spedizioni, attività del team e rischi di consegna.', live: 'Operazioni live', assetsSummary: '24 veicoli · 12 carichi attivi', stats: ['Ricavi di oggi', 'Chilometri attivi', 'Capacità utilizzata'], metrics: [['Veicoli attivi', 'su 24 veicoli'], ['Carichi in transito', '4 in arrivo oggi'], ['Team online', '7 autisti in servizio'], ['Puntualità', '+2,4% questo mese']], dispatch: ['Pannello spedizioni live', 'Rotte prioritarie e avanzamento attuale.', '12 attivi'], statuses: ['Domani', 'In transito', 'Ultimo miglio'], health: ['Stato operativo', 'Rotte in orario', 'Controllo ritardi', 'Avvisi critici'], activityTitle: 'Attività recente', activities: [['Lena ha assegnato il carico SF-2049 all’autista PT-19', '8 min fa'], ['Il veicolo DE-442 è entrato nella zona di consegna di Monaco', '21 min fa'], ['Finanza ha approvato il pagamento per Nord Cargo GmbH', '42 min fa'], ['Invito autista accettato da Adnan K.', '1 ora fa']], performance: ['Le prestazioni aziendali sono in crescita', 'Le consegne puntuali sono migliorate del 2,4% e i chilometri a vuoto sono diminuiti dell’8,1% questo mese.', 'Apri analisi'],
  },
  zh: {
    company: '物流公司', title: '运营概览', subtitle: '实时掌握车队调度、运输执行、团队活动和交付风险。', live: '实时运营', assetsSummary: '24 辆车 · 12 个活跃货单', stats: ['今日收入', '行驶公里数', '运力利用率'], metrics: [['活跃车辆', '共 24 辆车'], ['运输中货单', '4 单今日到达'], ['团队在线', '7 名司机值班'], ['准时率', '本月 +2.4%']], dispatch: ['实时调度看板', '优先路线及当前执行进度。', '12 个活跃'], statuses: ['明天', '运输中', '最后一公里'], health: ['运营状况', '按计划行驶', '延误关注', '严重警报'], activityTitle: '最近动态', activities: [['Lena 将货单 SF-2049 分配给司机 PT-19', '8 分钟前'], ['车辆 DE-442 已进入慕尼黑配送区', '21 分钟前'], ['财务已批准向 Nord Cargo GmbH 付款', '42 分钟前'], ['Adnan K. 已接受司机邀请', '1 小时前']], performance: ['公司绩效持续上升', '本月准时交付率提高 2.4%，空驶里程下降 8.1%。', '打开分析'],
  },
  es: {
    company: 'Empresa logística', title: 'Resumen de operaciones', subtitle: 'Un centro de mando en vivo para movimientos de flota, rendimiento de despacho, actividad del equipo y riesgos de entrega.', live: 'Operaciones en vivo', assetsSummary: '24 vehículos · 12 cargas activas', stats: ['Ingresos de hoy', 'Kilómetros activos', 'Capacidad utilizada'], metrics: [['Vehículos activos', 'de 24 vehículos'], ['Cargas en tránsito', '4 llegan hoy'], ['Equipo conectado', '7 conductores de servicio'], ['Puntualidad', '+2,4% este mes']], dispatch: ['Panel de despacho en vivo', 'Rutas prioritarias y progreso actual.', '12 activas'], statuses: ['Mañana', 'En tránsito', 'Última milla'], health: ['Estado operativo', 'Rutas según horario', 'Vigilancia de retrasos', 'Alertas críticas'], activityTitle: 'Actividad reciente', activities: [['Lena asignó la carga SF-2049 al conductor PT-19', 'hace 8 min'], ['El vehículo DE-442 entró en la zona de entrega de Múnich', 'hace 21 min'], ['Finanzas aprobó el pago a Nord Cargo GmbH', 'hace 42 min'], ['Adnan K. aceptó la invitación de conductor', 'hace 1 h']], performance: ['El rendimiento de la empresa está mejorando', 'Las entregas puntuales mejoraron un 2,4% y los kilómetros en vacío bajaron un 8,1% este mes.', 'Abrir analíticas'],
  },
  sr: {
    company: 'Logistička kompanija', title: 'Pregled operacija', subtitle: 'Kontrolni centar uživo za kretanje flote, učinak dispečera, aktivnosti tima i rizike isporuke.', live: 'Operacije uživo', assetsSummary: '24 vozila · 12 aktivnih tereta', stats: ['Prihod danas', 'Aktivni kilometri', 'Iskorišćenost kapaciteta'], metrics: [['Aktivna vozila', 'od 24 vozila u floti'], ['Tereti u tranzitu', '4 stižu danas'], ['Tim onlajn', '7 vozača na dužnosti'], ['Tačnost isporuke', '+2,4% ovog meseca']], dispatch: ['Dispečerska tabla uživo', 'Prioritetne rute i trenutni napredak realizacije.', '12 aktivnih'], statuses: ['Sutra', 'U tranzitu', 'Završna etapa'], health: ['Operativno stanje', 'Rute po rasporedu', 'Praćenje kašnjenja', 'Kritična upozorenja'], activityTitle: 'Nedavne aktivnosti', activities: [['Lena je dodelila teret SF-2049 vozaču PT-19', 'pre 8 min'], ['Vozilo DE-442 ušlo je u zonu isporuke Minhen', 'pre 21 min'], ['Finansije su odobrile isplatu za Nord Cargo GmbH', 'pre 42 min'], ['Adnan K. je prihvatio poziv za vozača', 'pre 1 h']], performance: ['Učinak kompanije raste', 'Tačnost isporuke poboljšana je za 2,4%, a prazni kilometri smanjeni su za 8,1% ovog meseca.', 'Otvori analitiku'],
  },
  sv: {
    company: 'Logistikföretag', title: 'Driftöversikt', subtitle: 'En livecentral för flottrörelser, transportledning, teamaktivitet och leveransrisker.', live: 'Liveverksamhet', assetsSummary: '24 fordon · 12 aktiva laster', stats: ['Intäkter idag', 'Aktiva kilometer', 'Utnyttjad kapacitet'], metrics: [['Aktiva fordon', 'av 24 flottfordon'], ['Laster på väg', '4 anländer idag'], ['Team online', '7 förare i tjänst'], ['Punktlighet', '+2,4 % denna månad']], dispatch: ['Live transporttavla', 'Prioriterade rutter och aktuella framsteg.', '12 aktiva'], statuses: ['I morgon', 'På väg', 'Sista sträckan'], health: ['Driftstatus', 'Rutter enligt tidtabell', 'Förseningsbevakning', 'Kritiska varningar'], activityTitle: 'Senaste aktivitet', activities: [['Lena tilldelade last SF-2049 till förare PT-19', 'för 8 min sedan'], ['Fordon DE-442 körde in i Münchens leveranszon', 'för 21 min sedan'], ['Ekonomi godkände betalningen till Nord Cargo GmbH', 'för 42 min sedan'], ['Förarinbjudan accepterades av Adnan K.', 'för 1 tim sedan']], performance: ['Företagets resultat förbättras', 'Leveranser i tid ökade med 2,4 % och tomkörningen minskade med 8,1 % denna månad.', 'Öppna analys'],
  },
  ar: {
    company: 'شركة لوجستية', title: 'نظرة عامة على العمليات', subtitle: 'مركز تحكم مباشر لحركة الأسطول وأداء الإرسال ونشاط الفريق ومخاطر التسليم.', live: 'عمليات مباشرة', assetsSummary: '24 مركبة · 12 حمولة نشطة', stats: ['إيرادات اليوم', 'الكيلومترات النشطة', 'السعة المستخدمة'], metrics: [['المركبات النشطة', 'من أصل 24 مركبة'], ['الحمولات قيد النقل', '4 تصل اليوم'], ['الفريق متصل', '7 سائقين في الخدمة'], ['الأداء في الموعد', '+2.4% هذا الشهر']], dispatch: ['لوحة الإرسال المباشر', 'المسارات ذات الأولوية وتقدم التنفيذ الحالي.', '12 نشطة'], statuses: ['غداً', 'قيد النقل', 'الميل الأخير'], health: ['الحالة التشغيلية', 'المسارات في الموعد', 'مراقبة التأخير', 'تنبيهات حرجة'], activityTitle: 'النشاط الأخير', activities: [['أسندت Lena الحمولة SF-2049 إلى السائق PT-19', 'منذ 8 دقائق'], ['دخلت المركبة DE-442 منطقة التسليم في ميونخ', 'منذ 21 دقيقة'], ['وافقت المالية على الدفع إلى Nord Cargo GmbH', 'منذ 42 دقيقة'], ['قبل Adnan K. دعوة السائق', 'منذ ساعة']], performance: ['أداء الشركة في تحسن', 'تحسن التسليم في الموعد بنسبة 2.4% وانخفضت الكيلومترات الفارغة بنسبة 8.1% هذا الشهر.', 'فتح التحليلات'],
  },
  pt: {
    company: 'Empresa logística', title: 'Visão geral das operações', subtitle: 'Um centro de comando em tempo real para movimentos da frota, desempenho da expedição, atividade da equipa e riscos de entrega.', live: 'Operações ao vivo', assetsSummary: '24 veículos · 12 cargas ativas', stats: ['Receita hoje', 'Quilómetros ativos', 'Capacidade utilizada'], metrics: [['Veículos ativos', 'de 24 veículos'], ['Cargas em trânsito', '4 chegam hoje'], ['Equipa online', '7 motoristas em serviço'], ['Pontualidade', '+2,4% este mês']], dispatch: ['Painel de expedição ao vivo', 'Rotas prioritárias e progresso atual da execução.', '12 ativas'], statuses: ['Amanhã', 'Em trânsito', 'Última milha'], health: ['Estado operacional', 'Rotas dentro do horário', 'Monitorização de atrasos', 'Alertas críticos'], activityTitle: 'Atividade recente', activities: [['Lena atribuiu a carga SF-2049 ao motorista PT-19', 'há 8 min'], ['O veículo DE-442 entrou na zona de entrega de Munique', 'há 21 min'], ['Finanças aprovou o pagamento à Nord Cargo GmbH', 'há 42 min'], ['Convite de motorista aceite por Adnan K.', 'há 1 h']], performance: ['O desempenho da empresa está a melhorar', 'As entregas pontuais melhoraram 2,4% e os quilómetros vazios caíram 8,1% este mês.', 'Abrir análises'],
  },
};

export const getCompanyOverviewCopy = (lang: Language) => COPY[(lang || 'en') as Locale] || COPY.en;
