import { useState, useEffect } from 'react';
import { Clock, MapPin, BarChart3 } from 'lucide-react';
import { MapContainer, TileLayer, Polyline, Marker, Popup } from 'react-leaflet';
import { Language, RouteLog } from '../../types';
import { MOCK_ROUTES } from '../../mockData';
import { getRouteInsights } from '../../services/geminiService';
import { ui } from '../../i18n';
import { cn } from '../../lib/cn';
import { Card } from '../ui/Card';

export const HistoryView = ({ lang }: { lang: Language }) => {
  const u = (key: string, fallback: string) => ui(lang, key, fallback);
  const [selectedRoute, setSelectedRoute] = useState<RouteLog>(MOCK_ROUTES[0]);
  const [insights, setInsights] = useState("");

  useEffect(() => {
    getRouteInsights(['Vienna', 'Prague', 'Berlin']).then(setInsights);
  }, [selectedRoute]);

  return (
    <div className="grid lg:grid-cols-12 gap-6">
      <div className="lg:col-span-4 space-y-4">
        <h2 className="text-xl font-bold dark:text-white">{u('history.routeHistory', 'Route History')}</h2>
        <div className="space-y-2">
          {MOCK_ROUTES.map(route => (
            <button 
              key={route.id}
              onClick={() => setSelectedRoute(route)}
              className={cn(
                "w-full p-4 rounded-2xl border text-left transition-all",
                selectedRoute.id === route.id ? "border-primary bg-primary/5" : "border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900"
              )}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold text-slate-400">{route.date}</span>
                <span className="text-xs font-bold text-primary">{route.distance}</span>
              </div>
              <div className="flex items-center gap-4 text-sm font-bold dark:text-white">
                <div className="flex items-center gap-1">
                  <Clock className="w-3 h-3 text-slate-400" />
                  {route.duration}
                </div>
                <div className="flex items-center gap-1">
                  <MapPin className="w-3 h-3 text-slate-400" />
                  {route.stops} {lang === 'bs' ? 'stajanja' : lang === 'de' ? 'Stopps' : 'stops'}
                </div>
              </div>
            </button>
          ))}
        </div>
      </div>
      <div className="lg:col-span-8 space-y-6">
        <Card title={u('history.routePath', 'Route Path')}>
          <div className="h-[400px] rounded-xl overflow-hidden relative">
            <MapContainer center={selectedRoute.path[0]} zoom={8} className="h-full w-full">
              <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
              <Polyline positions={selectedRoute.path} color="#00AEEF" weight={4} />
              {selectedRoute.path.map((pos, i) => (
                <Marker key={i} position={pos}>
                    <Popup>{lang === 'bs' ? 'Stajanje' : lang === 'de' ? 'Stopp' : 'Stop'} {i + 1}</Popup>
                  </Marker>
                ))}
              </MapContainer>
          </div>
        </Card>
        <Card title={u('history.aiRouteInsights', 'AI Route Insights')}>
          <div className="flex gap-4 items-start">
            <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center shrink-0">
              <BarChart3 className="text-primary w-5 h-5" />
            </div>
            <div>
              <p className="text-sm dark:text-slate-200 leading-relaxed italic">"{insights}"</p>
              <p className="text-[10px] text-slate-400 mt-2 uppercase font-bold">{u('history.generatedByAi', 'Generated by PathTracker.ai AI')}</p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
};


