import { useEffect, useState } from 'react';
import { Database, PlugZap } from 'lucide-react';
import { api } from '../../services/api';
import { Button } from '../ui/Button';

type Row = Record<string, any>;
type Props = { company: number; t: (key: string) => string; fail: (e: unknown) => void; canImport: boolean; canWrite: boolean; inputClass: string; panel: string; onImported: () => Promise<void> };
const defaults = { host: '', port: '1433', database: '', schema: 'dbo', username: '', password: '', allow_write: false, clerk_id: '0', outgoing_doc_type: '4200', incoming_doc_type: '4300', journal_doc_type: '4700' };
const today = () => new Intl.DateTimeFormat('sv-SE', { timeZone: 'Europe/Sarajevo' }).format(new Date());

export function PantheonPanel({ company, t, fail, canImport, canWrite, inputClass, panel, onImported }: Props) {
  const [form, setForm] = useState<Row>(defaults); const [saved, setSaved] = useState<Row | null>(null); const [busy, setBusy] = useState(false);
  const [test, setTest] = useState<Row | null>(null); const [type, setType] = useState('accounts'); const [rows, setRows] = useState<Row[]>([]);
  const [picked, setPicked] = useState<Record<string, Row>>({}); const [note, setNote] = useState(''); const [importResult, setImportResult] = useState<Row | null>(null);
  const [range, setRange] = useState({ from: `${today().slice(0, 8)}01`, to: today() }); const [exportResult, setExportResult] = useState<Row | null>(null);
  useEffect(() => { api.accounting.get<Row | null>(company, 'pantheon').then(r => { setSaved(r.data); if (r.data) setForm({ ...defaults, ...r.data, password: '' }); }).catch(fail); }, [company]); // eslint-disable-line react-hooks/exhaustive-deps
  const run = async (fn: () => Promise<void>) => { if (busy) return; setBusy(true); try { await fn(); } catch (e) { fail(e); } finally { setBusy(false); } };
  const key = (r: Row) => String(type === 'accounts' ? r.code : r.key);
  const field = (k: string, kind = 'text') => <label key={k} className="block text-xs font-medium text-slate-500">{t(`pantheon_${k}`)}<input className={`${inputClass} mt-1`} type={kind} value={String(form[k] ?? '')} autoComplete={kind === 'password' ? 'new-password' : 'off'} placeholder={k === 'password' && saved ? '••••••••' : undefined} onChange={e => setForm({ ...form, [k]: e.target.value })} /></label>;
  return <div className="space-y-4">
    <form className={`${panel} space-y-4`} onSubmit={e => { e.preventDefault(); void run(async () => { const r = await api.accounting.send<Row>(company, 'pantheon', { ...form, port: Number(form.port), clerk_id: Number(form.clerk_id), password: form.password || null }); setSaved(r.data); setForm({ ...form, password: '' }); }); }}>
      <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-bold"><PlugZap size={18} />{t('pantheon')}</h2>{saved?.last_test_status && <span className={`rounded-lg px-3 py-1 text-xs ${saved.last_test_status === 'ok' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{t(saved.last_test_status === 'ok' ? 'pantheon_connected' : 'failed')} · {String(saved.last_tested_at ?? '').slice(0, 16)}</span>}</div>
      <p className="text-sm text-slate-500">{t('pantheon_licence')}</p>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{field('host')}{field('port', 'number')}{field('database')}{field('schema')}{field('username')}{field('password', 'password')}{field('clerk_id', 'number')}</div>
      <div className="grid gap-3 sm:grid-cols-3">{field('outgoing_doc_type')}{field('incoming_doc_type')}{field('journal_doc_type')}</div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.allow_write} onChange={e => setForm({ ...form, allow_write: e.target.checked })} />{t('pantheon_allow_write')}</label>
      <div className="flex flex-wrap gap-2"><Button disabled={busy}>{t('save')}</Button><Button type="button" variant="outline" disabled={busy || !saved} onClick={() => void run(async () => { const r = await api.accounting.send<Row>(company, 'pantheon/test', {}); setTest(r.data); setSaved((await api.accounting.get<Row>(company, 'pantheon')).data); })}>{t('pantheon_test')}</Button></div>
      {test && <p className={`text-sm ${test.ok ? 'text-emerald-700' : 'text-rose-700'}`}>{test.ok ? `${t('pantheon_connected')} · ${test.accounts} ${t('accounts')} · ${test.subjects} ${t('partners')}` : test.error}</p>}
    </form>
    {saved && <section className={`${panel} space-y-4`}>
      <h2 className="flex items-center gap-2 font-bold"><Database size={18} />{t('pantheon_import')}</h2>
      <div className="flex flex-wrap gap-2">{['accounts', 'partners', 'taxes'].map(k => <Button key={k} size="sm" variant={type === k ? 'primary' : 'outline'} disabled={busy} onClick={() => void run(async () => { setType(k); setPicked({}); setImportResult(null); setRows((await api.accounting.get<Row[]>(company, `pantheon/preview?type=${k}`)).data); })}>{t(k === 'taxes' ? 'pantheon_taxes' : k)}</Button>)}</div>
      {type === 'taxes' && rows.length > 0 && <p className="text-sm text-amber-700">{t('noTaxAssumption')}</p>}
      {rows.length > 0 && <div className="max-h-[420px] overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-slate-500">{type !== 'taxes' && <th className="p-2"><input type="checkbox" aria-label={t('pantheon_select_all')} onChange={e => setPicked(e.target.checked ? Object.fromEntries(rows.filter(r => !r.exists).map(r => [key(r), { kind: r.kind, country_code: r.country_code }])) : {})} /></th>}{(type === 'accounts' ? ['code', 'name', 'kind', 'status'] : type === 'partners' ? ['name', 'tax_number', 'country_code', 'status'] : ['code', 'name', 'rate', 'pantheon_fiscal_code']).map(k => <th className="p-2" key={k}>{t(k)}</th>)}</tr></thead>
        <tbody>{rows.map(r => <tr key={key(r)} className="border-t border-slate-100 dark:border-slate-800">
          {type !== 'taxes' && <td className="p-2"><input type="checkbox" disabled={r.exists} checked={!!picked[key(r)]} onChange={e => setPicked(current => { const next = { ...current }; if (e.target.checked) next[key(r)] = { kind: r.kind, country_code: r.country_code }; else delete next[key(r)]; return next; })} /></td>}
          {type === 'accounts' && <><td className="p-2 font-mono">{r.code}</td><td className="p-2">{r.name}</td><td className="p-2"><select className={inputClass} disabled={r.exists} value={picked[key(r)]?.kind ?? r.kind ?? ''} onChange={e => setPicked({ ...picked, [key(r)]: { ...picked[key(r)], kind: e.target.value || null } })}><option value="">—</option>{['asset', 'liability', 'equity', 'income', 'expense'].map(k => <option key={k} value={k}>{t(k)}</option>)}</select></td><td className="p-2 text-xs">{r.exists ? t('pantheon_exists') : r.postable ? '' : t('pantheon_synthetic')}</td></>}
          {type === 'partners' && <><td className="p-2">{r.name}</td><td className="p-2">{r.tax_number ?? '—'}</td><td className="p-2"><input className={`${inputClass} w-20`} maxLength={2} disabled={r.exists} value={picked[key(r)]?.country_code ?? r.country_code ?? ''} onChange={e => setPicked({ ...picked, [key(r)]: { ...picked[key(r)], country_code: e.target.value.toUpperCase() || null } })} /></td><td className="p-2 text-xs">{r.exists ? t('pantheon_exists') : r.country}</td></>}
          {type === 'taxes' && <><td className="p-2 font-mono">{r.code}</td><td className="p-2">{r.name}</td><td className="p-2">{r.rate}</td><td className="p-2">{r.fiscal_code}</td></>}
        </tr>)}</tbody></table></div>}
      {type !== 'taxes' && rows.length > 0 && canImport && <form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); void run(async () => { const items = Object.entries(picked).map(([k, v]) => ({ [type === 'accounts' ? 'code' : 'key']: k, ...v })); const r = await api.accounting.send<Row>(company, 'pantheon/import', { type, items, review_note: note }); setImportResult(r.data); setRows((await api.accounting.get<Row[]>(company, `pantheon/preview?type=${type}`)).data); setPicked({}); await onImported(); }); }}>
        <label className="block flex-1 text-xs font-medium text-slate-500">{t('review_note')}<input className={`${inputClass} mt-1`} value={note} onChange={e => setNote(e.target.value)} required /></label><Button disabled={busy || !Object.keys(picked).length}>{t('pantheon_import')} ({Object.keys(picked).length})</Button></form>}
      {importResult && <p className="text-sm">{t('pantheon_imported')}: {importResult.imported}{importResult.skipped?.length ? ` · ${t('pantheon_skipped')}: ${importResult.skipped.map((s: Row) => `${s.key} (${t(`pantheon_${s.reason}`)})`).join(', ')}` : ''}</p>}
    </section>}
    {saved && <section className={`${panel} space-y-4`}>
      <h2 className="font-bold">{t('pantheon_export')}</h2><p className="text-sm text-slate-500">{t('pantheon_export_note')}</p>
      <div className="flex flex-wrap items-end gap-3">{(['from', 'to'] as const).map(k => <label key={k} className="block text-xs font-medium text-slate-500">{t(k)}<input type="date" className={`${inputClass} mt-1`} value={range[k]} onChange={e => setRange({ ...range, [k]: e.target.value })} /></label>)}
        <Button variant="outline" disabled={busy} onClick={() => void run(async () => setExportResult((await api.accounting.send<Row>(company, 'pantheon/export', { ...range, write: false })).data))}>{t('preview')}</Button>
        {canWrite && <Button disabled={busy || !saved.allow_write || !exportResult?.dry_run || !exportResult.ready} onClick={() => { if (window.confirm(t('pantheon_confirm_write'))) void run(async () => setExportResult((await api.accounting.send<Row>(company, 'pantheon/export', { ...range, write: true })).data)); }}>{t('pantheon_write')} ({exportResult?.ready ?? 0})</Button>}</div>
      {exportResult && <div className="space-y-2">{!exportResult.dry_run && <p className="text-sm text-emerald-700">{t('pantheon_exported')}: {exportResult.exported.map((e: Row) => e.pantheon_key).join(', ') || '0'}</p>}
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs text-slate-500">{['posting_date', 'pantheon_doc_type', 'document', 'debit', 'credit', 'status'].map(k => <th className="p-2" key={k}>{t(k)}</th>)}</tr></thead><tbody>{exportResult.documents.map((d: Row) => <tr key={d.entry_id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-2">{d.date}</td><td className="p-2 font-mono">{d.doc_type}</td><td className="p-2">{d.document}</td><td className="p-2">{d.debit}</td><td className="p-2">{d.credit}</td><td className={`p-2 text-xs ${d.problems.length ? 'text-rose-700' : 'text-emerald-700'}`}>{d.problems.length ? d.problems.join(' ') : t('pantheon_ready')}</td></tr>)}</tbody></table>{!exportResult.documents.length && <p className="p-4 text-center text-slate-500">{t('empty')}</p>}</div></div>}
    </section>}
  </div>;
}
