import type { Load } from '../../types';

/**
 * Ten fully-attributed demo shipments for the public landing page.
 *
 * They are shaped like API load records on purpose, so the real presentational components
 * (LenaLoadDetailsCard and friends) render them unchanged. Nothing here is fetched: the landing
 * page is pre-auth, so every authenticated screen it borrows from has to run on static data.
 */
export type DemoLoad = Record<string, unknown>;

export const LANDING_DEMO_LOADS: DemoLoad[] = [
  {
    id: 9001,
    title: 'Pharma pallets — Hamburg to Sarajevo',
    booking_reference: 'HAM-SJJ-214',
    status: 'in_transit',
    transport_type: 'road',
    cargo_type: 'FTL',
    goods_type: 'Pharmaceuticals',
    weight_kg: 24000,
    volume_m3: 68,
    pallets: 33,
    length_m: 13.6,
    width_m: 2.45,
    height_m: 2.7,
    temperature_min: 2,
    temperature_max: 8,
    budget: 2450,
    currency: 'EUR',
    payment_terms: '30 days',
    incoterm: 'DAP',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: true,
    is_urgent: false,
    characteristics: ['GDP'],
    distance_km: 1545,
    contact_name: 'Amina Hodžić',
    contact_phone: '+387 33 000 214',
    notes: 'Temperature log required at both ends.',
    stops: [
      { type: 'pickup', position: 1, city: 'Hamburg', country_code: 'DE', latitude: 53.5511, longitude: 9.9937, address: 'Hafen Hamburg, Terminal 3', window_starts_at: '2026-03-01T08:00', window_ends_at: '2026-03-01T12:00' },
      { type: 'delivery', position: 2, city: 'Sarajevo', country_code: 'BA', latitude: 43.8563, longitude: 18.4131, address: 'Sarajevo Hub, Rajlovac', window_starts_at: '2026-03-03T14:20', window_ends_at: '2026-03-03T18:00' },
    ],
  },
  {
    id: 9002,
    title: 'Retail electronics — Rotterdam to Zagreb',
    booking_reference: 'RTM-ZAG-118',
    status: 'posted',
    transport_type: 'road',
    cargo_type: 'FTL',
    goods_type: 'Electronics',
    weight_kg: 18500,
    volume_m3: 82,
    pallets: 30,
    length_m: 13.6,
    width_m: 2.45,
    height_m: 2.9,
    temperature_min: null,
    temperature_max: null,
    budget: 2150,
    currency: 'EUR',
    payment_terms: '45 days',
    incoterm: 'CPT',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: true,
    is_urgent: true,
    characteristics: ['TIR'],
    distance_km: 1290,
    contact_name: 'Bram de Vries',
    contact_phone: '+31 10 000 118',
    notes: 'High-value cargo — sealed trailer, no unaccompanied stops.',
    stops: [
      { type: 'pickup', position: 1, city: 'Rotterdam', country_code: 'NL', latitude: 51.9244, longitude: 4.4777, address: 'Waalhaven DC', window_starts_at: '2026-03-02T06:00', window_ends_at: '2026-03-02T10:00' },
      { type: 'delivery', position: 2, city: 'Zagreb', country_code: 'HR', latitude: 45.815, longitude: 15.9819, address: 'Zagreb Hub, Jankomir', window_starts_at: '2026-03-04T09:00', window_ends_at: '2026-03-04T15:00' },
    ],
  },
  {
    id: 9003,
    title: 'Frozen goods — Munich to Belgrade',
    booking_reference: 'MUC-BEG-402',
    status: 'posted',
    transport_type: 'road',
    cargo_type: 'FTL',
    goods_type: 'Frozen food',
    weight_kg: 21000,
    volume_m3: 70,
    pallets: 33,
    length_m: 13.6,
    width_m: 2.45,
    height_m: 2.6,
    temperature_min: -22,
    temperature_max: -18,
    budget: 1980,
    currency: 'EUR',
    payment_terms: '30 days',
    incoterm: 'DAP',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: true,
    is_urgent: false,
    characteristics: ['GDP'],
    distance_km: 905,
    contact_name: 'Lena Brandt',
    contact_phone: '+49 89 000 402',
    notes: 'Reefer must run continuously; download the temperature trace on delivery.',
    stops: [
      { type: 'pickup', position: 1, city: 'Munich', country_code: 'DE', latitude: 48.1351, longitude: 11.582, address: 'Munich Cold Store', window_starts_at: '2026-03-05T05:00', window_ends_at: '2026-03-05T09:00' },
      { type: 'delivery', position: 2, city: 'Belgrade', country_code: 'RS', latitude: 44.7866, longitude: 20.4489, address: 'Belgrade Distribution Centre', window_starts_at: '2026-03-06T12:00', window_ends_at: '2026-03-06T17:00' },
    ],
  },
  {
    id: 9004,
    title: 'Machine parts — Vienna to Ljubljana',
    booking_reference: 'VIE-LJU-077',
    status: 'posted',
    transport_type: 'road',
    cargo_type: 'LTL',
    goods_type: 'Machinery',
    weight_kg: 7400,
    volume_m3: 24,
    pallets: 11,
    length_m: 6.2,
    width_m: 2.4,
    height_m: 2.4,
    temperature_min: null,
    temperature_max: null,
    budget: 740,
    currency: 'EUR',
    payment_terms: '14 days',
    incoterm: 'EXW',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: false,
    is_urgent: false,
    characteristics: [],
    distance_km: 385,
    contact_name: 'Markus Bauer',
    contact_phone: '+43 1 000 077',
    notes: 'Forklift available at both ends.',
    stops: [
      { type: 'pickup', position: 1, city: 'Vienna', country_code: 'AT', latitude: 48.2082, longitude: 16.3738, address: 'Wien Süd Industrial Park', window_starts_at: '2026-03-02T13:00', window_ends_at: '2026-03-02T17:00' },
      { type: 'delivery', position: 2, city: 'Ljubljana', country_code: 'SI', latitude: 46.0569, longitude: 14.5058, address: 'BTC Logistics Park', window_starts_at: '2026-03-03T08:00', window_ends_at: '2026-03-03T12:00' },
    ],
  },
  {
    id: 9005,
    title: 'ADR chemicals — Antwerp to Budapest',
    booking_reference: 'ANR-BUD-533',
    status: 'posted',
    transport_type: 'road',
    cargo_type: 'FTL',
    goods_type: 'Chemicals',
    weight_kg: 19800,
    volume_m3: 60,
    pallets: 26,
    length_m: 13.6,
    width_m: 2.45,
    height_m: 2.6,
    temperature_min: null,
    temperature_max: null,
    budget: 2790,
    currency: 'EUR',
    payment_terms: '30 days',
    incoterm: 'DAP',
    is_negotiable: true,
    requires_adr: true,
    cmr_required: true,
    is_urgent: false,
    characteristics: ['TIR'],
    distance_km: 1310,
    contact_name: 'Sofie Peeters',
    contact_phone: '+32 3 000 533',
    notes: 'ADR class 3. Driver ADR certificate and orange plates required.',
    stops: [
      { type: 'pickup', position: 1, city: 'Antwerp', country_code: 'BE', latitude: 51.2194, longitude: 4.4025, address: 'Antwerp Chemical Terminal', window_starts_at: '2026-03-07T07:00', window_ends_at: '2026-03-07T11:00' },
      { type: 'delivery', position: 2, city: 'Budapest', country_code: 'HU', latitude: 47.4979, longitude: 19.0402, address: 'Budapest Industrial Estate', window_starts_at: '2026-03-09T10:00', window_ends_at: '2026-03-09T16:00' },
    ],
  },
  {
    id: 9006,
    title: 'Air freight — Frankfurt to Istanbul',
    booking_reference: 'FRA-IST-908',
    status: 'posted',
    transport_type: 'air',
    cargo_type: 'Air cargo',
    goods_type: 'Medical devices',
    weight_kg: 2400,
    volume_m3: 14,
    pallets: 6,
    length_m: 3.2,
    width_m: 2.2,
    height_m: 1.6,
    temperature_min: 15,
    temperature_max: 25,
    budget: 5400,
    currency: 'EUR',
    payment_terms: 'Prepaid',
    incoterm: 'CIP',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: false,
    is_urgent: true,
    characteristics: ['MED (medicine)'],
    distance_km: 1870,
    contact_name: 'Nils Krüger',
    contact_phone: '+49 69 000 908',
    notes: 'AWB required. Security screening booked at origin.',
    stops: [
      { type: 'pickup', position: 1, city: 'Frankfurt', country_code: 'DE', latitude: 50.1109, longitude: 8.6821, address: 'FRA Cargo City Süd', window_starts_at: '2026-03-04T04:00', window_ends_at: '2026-03-04T08:00' },
      { type: 'delivery', position: 2, city: 'Istanbul', country_code: 'TR', latitude: 41.0082, longitude: 28.9784, address: 'IST Cargo Terminal', window_starts_at: '2026-03-04T20:00', window_ends_at: '2026-03-05T02:00' },
    ],
  },
  {
    id: 9007,
    title: 'Sea container — Shanghai to Koper',
    booking_reference: 'SHA-KOP-611',
    status: 'posted',
    transport_type: 'sea',
    cargo_type: '40HC',
    goods_type: 'Consumer goods',
    weight_kg: 21500,
    volume_m3: 67,
    pallets: 24,
    length_m: 12.03,
    width_m: 2.35,
    height_m: 2.69,
    temperature_min: null,
    temperature_max: null,
    budget: 3250,
    currency: 'USD',
    payment_terms: 'Collect',
    incoterm: 'FOB',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: false,
    is_urgent: false,
    characteristics: ['BULK'],
    distance_km: 17400,
    contact_name: 'Wei Zhang',
    contact_phone: '+86 21 000 611',
    notes: 'SeaWaybill. Customs clearance handled at Koper.',
    stops: [
      { type: 'pickup', position: 1, city: 'Shanghai', country_code: 'CN', latitude: 31.2304, longitude: 121.4737, address: 'Yangshan Deep-Water Port', window_starts_at: '2026-03-01T00:00', window_ends_at: '2026-03-02T00:00' },
      { type: 'delivery', position: 2, city: 'Koper', country_code: 'SI', latitude: 45.5481, longitude: 13.7302, address: 'Luka Koper, Terminal II', window_starts_at: '2026-04-02T00:00', window_ends_at: '2026-04-03T00:00' },
    ],
  },
  {
    id: 9008,
    title: 'Rail block — Duisburg to Warsaw',
    booking_reference: 'DUI-WAW-245',
    status: 'posted',
    transport_type: 'rail',
    cargo_type: 'Intermodal',
    goods_type: 'Automotive parts',
    weight_kg: 26000,
    volume_m3: 76,
    pallets: 32,
    length_m: 13.6,
    width_m: 2.45,
    height_m: 2.7,
    temperature_min: null,
    temperature_max: null,
    budget: 1650,
    currency: 'EUR',
    payment_terms: '30 days',
    incoterm: 'CPT',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: false,
    is_urgent: false,
    characteristics: [],
    distance_km: 980,
    contact_name: 'Piotr Nowak',
    contact_phone: '+48 22 000 245',
    notes: 'CIM consignment note. Terminal-to-terminal.',
    stops: [
      { type: 'pickup', position: 1, city: 'Duisburg', country_code: 'DE', latitude: 51.4344, longitude: 6.7623, address: 'Duisburg Intermodal Terminal', window_starts_at: '2026-03-06T09:00', window_ends_at: '2026-03-06T15:00' },
      { type: 'delivery', position: 2, city: 'Warsaw', country_code: 'PL', latitude: 52.2297, longitude: 21.0122, address: 'Warszawa Praga Terminal', window_starts_at: '2026-03-08T07:00', window_ends_at: '2026-03-08T13:00' },
    ],
  },
  {
    id: 9009,
    title: 'Storage — 120 pallets in Sarajevo',
    booking_reference: 'SJJ-STO-330',
    status: 'posted',
    transport_type: 'warehouse',
    for_storage: true,
    cargo_type: 'Palletised',
    goods_type: 'Beverages',
    storage_type: 'Ambient',
    weight_kg: 96000,
    volume_m3: 210,
    pallets: 120,
    temperature_min: null,
    temperature_max: null,
    budget: 1440,
    currency: 'EUR',
    payment_terms: 'Monthly',
    rate_unit: 'per_pallet_month',
    is_negotiable: true,
    requires_adr: false,
    is_urgent: false,
    characteristics: [],
    storage_start_date: '2026-03-10',
    storage_end_date: '2026-06-10',
    is_storage_ongoing: false,
    handling_requirements: ['Storage', 'Loading', 'Unloading'],
    handling_equipment: ['Forklifts', 'Dock Doors'],
    contact_name: 'Emir Selimović',
    contact_phone: '+387 33 000 330',
    notes: 'Racked storage, monthly stock report expected.',
    stops: [
      { type: 'pickup', position: 1, city: 'Mostar', country_code: 'BA', latitude: 43.3438, longitude: 17.8078, address: 'Mostar Bottling Plant', window_starts_at: '2026-03-10T08:00', window_ends_at: '2026-03-10T14:00' },
      { type: 'delivery', position: 2, city: 'Sarajevo', country_code: 'BA', latitude: 43.8563, longitude: 18.4131, address: 'Freightbook Warehousing Co.', window_starts_at: '2026-03-10T16:00', window_ends_at: '2026-03-10T20:00' },
    ],
  },
  {
    id: 9010,
    title: 'Express LTL — Milan to Graz',
    booking_reference: 'MIL-GRZ-159',
    status: 'posted',
    transport_type: 'road',
    cargo_type: 'LTL',
    goods_type: 'Textiles',
    weight_kg: 3200,
    volume_m3: 18,
    pallets: 8,
    length_m: 4.8,
    width_m: 2.4,
    height_m: 2.2,
    temperature_min: null,
    temperature_max: null,
    budget: 610,
    currency: 'EUR',
    payment_terms: '14 days',
    incoterm: 'DAP',
    is_negotiable: true,
    requires_adr: false,
    cmr_required: true,
    is_urgent: true,
    characteristics: [],
    distance_km: 640,
    contact_name: 'Giulia Rossi',
    contact_phone: '+39 02 000 159',
    notes: 'Tail lift needed at delivery — no dock on site.',
    stops: [
      { type: 'pickup', position: 1, city: 'Milan', country_code: 'IT', latitude: 45.4642, longitude: 9.19, address: 'Milano Sud Logistics', window_starts_at: '2026-03-03T07:00', window_ends_at: '2026-03-03T11:00' },
      { type: 'delivery', position: 2, city: 'Graz', country_code: 'AT', latitude: 47.0707, longitude: 15.4395, address: 'Graz West Depot', window_starts_at: '2026-03-04T08:00', window_ends_at: '2026-03-04T12:00' },
    ],
  },
];

/**
 * The same demo shipments in the frontend `Load` shape, so the real exchange card (LoadItem) can
 * render them exactly as it renders live freight.
 */
export const LANDING_DEMO_LOAD_ITEMS: Load[] = LANDING_DEMO_LOADS.map((row) => {
  const stops = (row.stops as Array<Record<string, unknown>>) || [];
  const from = stops[0];
  const to = stops[stops.length - 1];
  const place = (stop: Record<string, unknown> | undefined) =>
    [stop?.city, stop?.country_code].filter(Boolean).join(', ');

  return {
    id: String(row.id),
    title: String(row.title || ''),
    // LoadItem prints the unit itself, so this is the bare number.
    weight: Number(row.weight_kg || 0).toLocaleString(),
    price: `${String(row.currency || 'EUR')} ${Number(row.budget || 0).toLocaleString()}`,
    pickup: place(from),
    delivery: place(to),
    pickupAt: String(from?.window_starts_at || ''),
    date: String(from?.window_starts_at || '').slice(0, 10),
    author: String(row.contact_name || 'Freightbook.ai'),
    status: 'Posted',
    cargoType: String(row.cargo_type || ''),
    goodsType: String(row.goods_type || ''),
    paymentTerms: String(row.payment_terms || ''),
    eta: String(to?.window_starts_at || '').replace('T', ' ').slice(0, 16),
    transportType: row.transport_type as Load['transportType'],
    forStorage: Boolean(row.for_storage),
    storageType: row.storage_type ? String(row.storage_type) : undefined,
    budget: Number(row.budget || 0),
    isNegotiable: Boolean(row.is_negotiable),
    requiresAdr: Boolean(row.requires_adr),
    cmrRequired: Boolean(row.cmr_required),
    urgency: row.is_urgent ? 'Express' : 'Standard',
    volume: Number(row.volume_m3 || 0) || undefined,
    pallets: Number(row.pallets || 0) || undefined,
    length: Number(row.length_m || 0) || undefined,
    width: Number(row.width_m || 0) || undefined,
    height: Number(row.height_m || 0) || undefined,
    temperatureMin: row.temperature_min === null ? undefined : Number(row.temperature_min),
    temperatureMax: row.temperature_max === null ? undefined : Number(row.temperature_max),
    incoterms: row.incoterm ? String(row.incoterm) : undefined,
    bookingReference: String(row.booking_reference || ''),
    trackingNumber: String(row.booking_reference || ''),
    pickupWindowStart: String(from?.window_starts_at || ''),
    pickupWindowEnd: String(from?.window_ends_at || ''),
    deliveryWindowStart: String(to?.window_starts_at || ''),
    deliveryWindowEnd: String(to?.window_ends_at || ''),
  };
});
