// Values are owned by backend/resources/lena/schema.json.
import { lenaOptions, getLenaCatalog } from '../../lib/lenaCatalog';

export const INCOTERM_OPTIONS = lenaOptions('INCOTERM_OPTIONS');
export const VEHICLE_OPTIONS = lenaOptions('VEHICLE_OPTIONS');
export const BODY_TYPE_OPTIONS = lenaOptions('BODY_TYPE_OPTIONS');
export const ROAD_CHARACTERISTIC_OPTIONS = lenaOptions('ROAD_CHARACTERISTIC_OPTIONS');
export const AIR_CHARACTERISTIC_OPTIONS = lenaOptions('AIR_CHARACTERISTIC_OPTIONS');
export const SEA_CHARACTERISTIC_OPTIONS = lenaOptions('SEA_CHARACTERISTIC_OPTIONS');
export const SEA_BL_TYPE_OPTIONS = lenaOptions('SEA_BL_TYPE_OPTIONS');
export const RAIL_DOCUMENT_TYPE_OPTIONS = lenaOptions('RAIL_DOCUMENT_TYPE_OPTIONS');
export const SEA_PAYMENT_TERMS_OPTIONS = lenaOptions('SEA_PAYMENT_TERMS_OPTIONS');
export const LOADING_EQUIPMENT_OPTIONS = lenaOptions('LOADING_EQUIPMENT_OPTIONS');
export const AIR_LOADING_EQUIPMENT_OPTIONS = lenaOptions('AIR_LOADING_EQUIPMENT_OPTIONS');
export const SEA_LOADING_EQUIPMENT_OPTIONS = lenaOptions('SEA_LOADING_EQUIPMENT_OPTIONS');
export const RAIL_LOADING_EQUIPMENT_OPTIONS = lenaOptions('RAIL_LOADING_EQUIPMENT_OPTIONS');
export const AIR_SPECIAL_REQUIREMENT_OPTIONS = lenaOptions('AIR_SPECIAL_REQUIREMENT_OPTIONS');
export const AIR_TAIL_LIFT_REQUIREMENT = String(getLenaCatalog().option_groups.AIR_TAIL_LIFT_REQUIREMENT);
export const AIR_TRANSPORT_MODE_OPTIONS = lenaOptions('AIR_TRANSPORT_MODE_OPTIONS');
export const DELIVERY_PROOF_OPTIONS = lenaOptions('DELIVERY_PROOF_OPTIONS');
export const CONTACT_OPTIONS = lenaOptions('CONTACT_OPTIONS');
export const CLOSED_EXCHANGE_OPTIONS = lenaOptions('CLOSED_EXCHANGE_OPTIONS');
export const LOAD_REQUIREMENT_OPTIONS = lenaOptions('LOAD_REQUIREMENT_OPTIONS');
export const WAREHOUSE_STORAGE_TYPE_OPTIONS = lenaOptions('WAREHOUSE_STORAGE_TYPE_OPTIONS');
export const WAREHOUSE_EQUIPMENT_OPTIONS = lenaOptions('WAREHOUSE_EQUIPMENT_OPTIONS');
export const WAREHOUSE_HANDLING_REQUIREMENT_OPTIONS = lenaOptions('WAREHOUSE_HANDLING_REQUIREMENT_OPTIONS');
export const WAREHOUSE_RATE_UNIT_OPTIONS = lenaOptions('WAREHOUSE_RATE_UNIT_OPTIONS');
