import { Offer } from './FrightTypes';

export const GLOBAL_OFFERS: Offer[] = [
  {
    id: 'one',
    carrier: 'One',
    badge: 'ONE',
    origin: 'Shanghai, CN',
    destination: 'Odesa, UA',
    originPort: 'Shanghai',
    transitDays: 96,
    freeDays: 40,
    priceUsd: 1120,
  },
  {
    id: 'cmacgm',
    carrier: 'CMA CGM',
    badge: 'CMA',
    origin: 'Shanghai, CN',
    destination: 'Odesa, UA',
    originPort: 'Shanghai',
    transitDays: 72,
    freeDays: 40,
    priceUsd: 1310,
  },
  {
    id: 'maersk',
    carrier: 'Maersk',
    badge: 'M',
    origin: 'Ningbo, CN',
    destination: 'Hamburg, DE',
    originPort: 'Ningbo',
    transitDays: 84,
    freeDays: 40,
    priceUsd: 1320,
  },
  {
    id: 'msc',
    carrier: 'MSC',
    badge: 'MSC',
    origin: 'Shenzhen, CN',
    destination: 'Rotterdam, NL',
    originPort: 'Yantian',
    transitDays: 76,
    freeDays: 35,
    priceUsd: 1240,
  },
  {
    id: 'hapag',
    carrier: 'Hapag-Lloyd',
    badge: 'HL',
    origin: 'Qingdao, CN',
    destination: 'Gdansk, PL',
    originPort: 'Qingdao',
    transitDays: 88,
    freeDays: 42,
    priceUsd: 1295,
  },
];
