import { toSerbianCyrillic } from '../../lib/serbianCyrillic';
const en = {
 title: 'LTL / LCL Planning', subtitle: 'Plan every piece. See the whole load.', equipment: 'Equipment', vehicle: 'Registered vehicle', custom: 'Container / custom dimensions',
 exterior: 'Exterior', dimensions: 'Inside dimensions', loading: 'Door / loading', top: 'Bird’s-eye view', side: 'Side view', warehouse: 'Warehouse',
 shipments: 'Shipments', add: 'Add cargo', name: 'Cargo name', customer: 'Customer', length: 'Length', width: 'Width', height: 'Height', weight: 'Weight', payload: 'Payload',
 doorWidth: 'Door width', doorHeight: 'Door height', pieces: 'Pieces', shape: 'Shape', box: 'Box', pallet: 'Pallet', pipe: 'Pipe', drum: 'Drum', stackable: 'May support another unit',
 pickup: 'Pickup address', delivery: 'Delivery address / port', documents: 'Documents / handling notes', auto: 'Auto Plan', save: 'Save in this browser', export: 'Export plan', import: 'Import plan',
 utilization: 'Equipment utilization', volume: 'Bounding volume', sequence: 'Loading sequence', empty: 'Add cargo to start planning.', placed: 'Placed', pending: 'Unplaced',
 remove: 'Remove', rotate: 'Rotate cargo', reset: 'Reset view', zoomIn: 'Zoom in', zoomOut: 'Zoom out', fullscreen: 'Full screen', cancel: 'Cancel',
 invalid: 'Check dimensions and weight. Placement must fit, clear the door, avoid collisions and have support.', saved: 'Plan saved in this browser.', failed: 'Could not save or read the plan.',
 hint: 'Drag cargo to move it. Drag empty space to orbit; scroll to zoom. Select a unit to edit its position.',
 estimate: 'Planning estimate. Confirm actual equipment, load securing and stacking strength. Open Top overheight requires a separate transport check.',
 defaults: 'Dimensions are editable planning defaults. Confirm them against the actual equipment.', fleetFailed: 'Registered vehicles could not be loaded.',
 position: 'Position (m)', apply: 'Apply position', floor: 'Occupied length', total: 'Total', unavailable: '3D rendering is unavailable. Enable WebGL and reload.',
 fromTracking: 'Current loads from tracking', trackingSearch: 'Search by reference, route or company', trackingLoading: 'Loading current loads…', trackingFailed: 'Tracking loads could not be loaded.', trackingEmpty: 'No current loads found.', use: 'Use', inPlan: 'In plan',
 trackingNote: 'Choosing a load fills the form below. Load totals are split per pallet; check sizes before adding.',
 cargoDimensions: 'Dimensions (m)', planName: 'Plan name', up: 'Earlier', down: 'Later', overheight: 'Overheight', open: 'Open Top', sample: 'Load example', countLimit: 'A plan supports up to 300 pieces.',
};
type Labels = typeof en;
const bs: Labels = {
 title:'LTL / LCL planiranje',subtitle:'Planirajte svaki komad. Pregledajte cijeli teret.',equipment:'Vozilo / kontejner',vehicle:'Registrovano vozilo',custom:'Kontejner / prilagođene dimenzije',
 exterior:'Vanjski prikaz',dimensions:'Unutrašnje dimenzije',loading:'Vrata / utovar',top:'Ptičja perspektiva',side:'Bočni prikaz',warehouse:'Skladište',
 shipments:'Pošiljke',add:'Dodaj teret',name:'Naziv tereta',customer:'Kupac',length:'Dužina',width:'Širina',height:'Visina',weight:'Težina',payload:'Nosivost',doorWidth:'Širina vrata',doorHeight:'Visina vrata',pieces:'Komadi',shape:'Oblik',box:'Kutija',pallet:'Paleta',pipe:'Cijev',drum:'Bačva',stackable:'Dozvoljeno slaganje drugog komada na ovaj',
 pickup:'Adresa preuzimanja',delivery:'Adresa isporuke / luka',documents:'Dokumenti / napomene za rukovanje',auto:'Automatski raspored',save:'Sačuvaj u ovom pregledniku',export:'Izvezi plan',import:'Uvezi plan',
 utilization:'Iskorištenost prostora',volume:'Zapremina gabarita',sequence:'Redoslijed utovara',empty:'Dodajte teret za početak planiranja.',placed:'Postavljeno',pending:'Nepostavljeno',remove:'Ukloni',rotate:'Rotiraj teret',reset:'Vrati prikaz',zoomIn:'Uvećaj',zoomOut:'Umanji',fullscreen:'Cijeli ekran',cancel:'Odustani',
 invalid:'Provjerite dimenzije i težinu. Teret mora stati, proći kroz vrata, imati oslonac i ne preklapati se.',saved:'Plan je sačuvan u ovom pregledniku.',failed:'Plan nije moguće sačuvati ili pročitati.',hint:'Povucite teret za pomjeranje. Povucite prazan prostor za rotaciju; točkićem zumirajte. Odaberite komad za unos položaja.',
 estimate:'Procjena za planiranje. Potvrdite opremu, osiguranje tereta i nosivost pri slaganju. Previsok teret u Open Top kontejneru zahtijeva posebnu provjeru transporta.',defaults:'Dimenzije su prilagodljive početne vrijednosti. Potvrdite ih prema stvarnoj opremi.',fleetFailed:'Registrovana vozila nije moguće učitati.',position:'Položaj (m)',apply:'Primijeni položaj',floor:'Zauzeta dužina',total:'Ukupno',unavailable:'3D prikaz nije dostupan. Omogućite WebGL i ponovo učitajte.',fromTracking:'Trenutni tereti iz praćenja',trackingSearch:'Pretraga po referenci, ruti ili kompaniji',trackingLoading:'Učitavanje trenutnih tereta…',trackingFailed:'Terete iz praćenja nije moguće učitati.',trackingEmpty:'Nema trenutnih tereta.',use:'Koristi',inPlan:'U planu',trackingNote:'Odabrani teret popunjava obrazac ispod. Ukupne vrijednosti dijele se po paleti; provjerite dimenzije prije dodavanja.',cargoDimensions:'Dimenzije (m)',planName:'Naziv plana',up:'Ranije',down:'Kasnije',overheight:'Prekoračena visina',open:'Open Top',sample:'Učitaj primjer',countLimit:'Plan podržava do 300 komada.',
};
const de: Labels = {
 title:'LTL / LCL Ladeplanung',subtitle:'Jedes Stück planen. Die ganze Ladung sehen.',equipment:'Laderaum',vehicle:'Registriertes Fahrzeug',custom:'Container / eigene Maße',exterior:'Außenansicht',dimensions:'Innenmaße',loading:'Tür / Beladung',top:'Draufsicht',side:'Seitenansicht',warehouse:'Lager',
 shipments:'Sendungen',add:'Ladung hinzufügen',name:'Ladungsname',customer:'Kunde',length:'Länge',width:'Breite',height:'Höhe',weight:'Gewicht',payload:'Nutzlast',doorWidth:'Türbreite',doorHeight:'Türhöhe',pieces:'Stück',shape:'Form',box:'Kiste',pallet:'Palette',pipe:'Rohr',drum:'Fass',stackable:'Weitere Einheit darf darauf stehen',pickup:'Abholadresse',delivery:'Lieferadresse / Hafen',documents:'Dokumente / Handhabung',auto:'Automatisch planen',save:'In diesem Browser speichern',export:'Plan exportieren',import:'Plan importieren',utilization:'Laderaumauslastung',volume:'Hüllvolumen',sequence:'Ladereihenfolge',empty:'Ladung hinzufügen, um zu beginnen.',placed:'Platziert',pending:'Nicht platziert',remove:'Entfernen',rotate:'Ladung drehen',reset:'Ansicht zurücksetzen',zoomIn:'Vergrößern',zoomOut:'Verkleinern',fullscreen:'Vollbild',cancel:'Abbrechen',invalid:'Maße und Gewicht prüfen. Ladung muss passen, durch die Tür gehen, gestützt sein und darf sich nicht überschneiden.',saved:'Plan in diesem Browser gespeichert.',failed:'Plan konnte nicht gespeichert oder gelesen werden.',hint:'Ladung zum Verschieben ziehen. Leeren Raum zum Drehen ziehen; mit dem Mausrad zoomen. Einheit für Positionseingabe auswählen.',estimate:'Planungsschätzung. Tatsächliche Ausrüstung, Ladungssicherung und Stapelfestigkeit bestätigen. Überhöhe bei Open Top erfordert eine gesonderte Transportprüfung.',defaults:'Maße sind anpassbare Planungswerte. Mit der tatsächlichen Ausrüstung abgleichen.',fleetFailed:'Registrierte Fahrzeuge konnten nicht geladen werden.',position:'Position (m)',apply:'Position übernehmen',floor:'Belegte Länge',total:'Gesamt',unavailable:'3D nicht verfügbar. WebGL aktivieren und neu laden.',fromTracking:'Aktuelle Ladungen aus der Sendungsverfolgung',trackingSearch:'Nach Referenz, Route oder Firma suchen',trackingLoading:'Aktuelle Ladungen werden geladen…',trackingFailed:'Ladungen aus der Sendungsverfolgung konnten nicht geladen werden.',trackingEmpty:'Keine aktuellen Ladungen gefunden.',use:'Übernehmen',inPlan:'Im Plan',trackingNote:'Die gewählte Ladung füllt das Formular unten. Gesamtwerte werden pro Palette aufgeteilt; Maße vor dem Hinzufügen prüfen.',cargoDimensions:'Maße (m)',planName:'Planname',up:'Früher',down:'Später',overheight:'Überhöhe',open:'Open Top',sample:'Beispiel laden',countLimit:'Ein Plan unterstützt bis zu 300 Stück.',
};
const hr: Labels = { ...bs, vehicle:'Registrirano vozilo', volume:'Volumen gabarita', save:'Spremi u ovom pregledniku',saved:'Plan je spremljen u ovom pregledniku.',failed:'Plan nije moguće spremiti ili pročitati.',fleetFailed:'Registrirana vozila nije moguće učitati.',sample:'Učitaj primjer' };
const sr: Labels = { ...bs, dimensions:'Unutrašnje dimenzije', trackingNote:'Odabrani teret popunjava obrazac ispod. Ukupne vrednosti dele se po paleti; proverite dimenzije pre dodavanja.', sequence:'Redosled utovara', length:'Dužina', apply:'Primeni položaj', hint:'Prevucite teret za pomeranje. Prevucite prazan prostor za rotaciju; točkićem zumirajte. Odaberite komad za unos položaja.', sample:'Učitaj primer' };
export function planningLabels(lang?: string | null): Labels {
  if (lang === 'sr') return Object.fromEntries(Object.entries(sr).map(([k,v]) => [k,toSerbianCyrillic(v)])) as Labels;
  return ({ en, bs, hr, de } as Record<string, Labels>)[lang ?? 'en'] ?? en;
}
