import { useMemo, useState } from 'react';
import { Hash, MapPin, Package, Phone, Truck, X } from 'lucide-react';
import { MapContainer, Marker, Polyline, TileLayer } from 'react-leaflet';
import type { Language, Load, Role } from '../../types';
import { ui } from '../../i18n';
import { api } from '../../services/api';
import { confirmAction, showError, showSuccess } from '../../lib/swal';
import { estimateLoadDistanceKm, getPlaceCoord } from '../../lib/loadGeo';
import { CustomsDocumentList } from './CustomsDocumentList';
import { RouteMapModal } from '../maps/RouteMapModal';

type Props = { open: boolean; load: Load | null; onClose: () => void; lang: Language; role?: Role; userId?: number; companyIds?: number[]; onEdit?: (load: Load) => void; onChanged?: () => void; onOperationsOpen?: (workspaceId: number, loadId: string) => void; warehouseMovementId?: string | null; onWarehouseMovementChanged?: () => void };
const text = (item: unknown, fallback = '-') => item == null || item === '' ? fallback : String(item);
const dateLabel = (item: unknown) => { if (!item) return '-'; const date = new Date(String(item)); return Number.isNaN(date.getTime()) ? String(item) : new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(date); };
const Metric = ({ icon: Icon, label, children }: { icon: typeof Package; label: string; children: React.ReactNode }) => <div className="flex min-w-0 items-center gap-2 border-r border-[#e4eaf2] px-4 last:border-0"><Icon className="h-4 w-4 shrink-0 text-[#2d5b9e]" /><div className="min-w-0"><p className="text-[10px] font-medium text-[#8390a5]">{label}</p><p className="truncate text-[11px] font-bold text-[#23314a]">{children}</p></div></div>;
const Info = ({ label, value }: { label: string; value: string }) => <div className="flex justify-between gap-2 border-b border-[#eff2f6] pb-2"><span className="text-[#71819a]">{label}</span><strong className="truncate text-right text-[#253a5d]">{value}</strong></div>;
const Stop = ({ label, place, tone, last }: { label: string; place: string; tone: string; last?: boolean }) => <div className="flex gap-2 pt-3"><div className="flex flex-col items-center"><span className={`h-3 w-3 rounded-full ${tone}`} />{!last && <span className="h-8 border-l border-dashed border-[#b9c6d8]" />}</div><div><p className="text-[10px] font-extrabold">{label}</p><p className="text-[10px] text-[#6d7d95]">{place}</p></div></div>;

export const LoadDetailsPrebookReference = ({ open, load, onClose, lang, onEdit, onChanged, onOperationsOpen }: Props) => {
  const u = (key: string, fallback: string) => ui(lang, key, fallback);
  const [routeOpen, setRouteOpen] = useState(false);
  const [booking, setBooking] = useState(false);
  const pickupPosition = load?.pickupPosition ?? (load?.pickup ? getPlaceCoord(load.pickup) : undefined);
  const deliveryPosition = load?.deliveryPosition ?? (load?.delivery ? getPlaceCoord(load.delivery) : undefined);
  const center = useMemo<[number, number] | null>(() => pickupPosition && deliveryPosition ? [(pickupPosition[0] + deliveryPosition[0]) / 2, (pickupPosition[1] + deliveryPosition[1]) / 2] : null, [pickupPosition, deliveryPosition]);
  if (!open || !load) return null;
  const pickup = text(load.pickup); const delivery = text(load.delivery); const price = text(load.price); const currency = price.split(' ')[0] || 'EUR';
  const distance = load.pickup && load.delivery ? `${Math.round(estimateLoadDistanceKm(load.pickup, load.delivery)).toLocaleString()} km` : '-'; const canRoute = Boolean(pickupPosition && deliveryPosition && center);
  const book = async () => { if (booking) return; const confirmed = await confirmAction({ title: u('reservation.requestTitle', 'Request booking'), text: u('reservation.confirmIntro', 'Submit a reservation request for this load?'), confirmText: u('reservation.submit', 'Submit reservation request'), cancelText: u('common.cancel', 'Cancel') }); if (!confirmed) return; setBooking(true); try { await api.loads.book(load.id); void showSuccess(u('reservation.submittedTitle', 'Reservation request sent'), u('reservation.submittedText', 'The customer must approve it before the load is assigned.')); onChanged?.(); onClose(); } catch (error) { void showError(u('legacy.loadDetails.bookFailedTitle', 'Could not book this load'), error instanceof Error ? error.message : undefined); } finally { setBooking(false); } };
  return <div className="fixed inset-0 z-[140] flex h-[100dvh] w-screen overflow-hidden bg-[#f5f8fc] font-sans text-[#23314a]"><div className="flex h-full min-w-0 flex-1 flex-col overflow-hidden bg-white">
    <header className="flex shrink-0 items-start justify-between border-b border-[#e5ebf3] px-5 py-3 sm:px-6"><div className="min-w-0"><div className="flex items-center gap-2 text-[10px] font-bold"><span className="rounded-full bg-[#e2f8ed] px-2 py-1 text-[#1b9a63]">{text(load.status, 'Available')}</span><span className="text-[#6e7f99]">#{text(load.trackingNumber, load.id)}</span></div><h1 className="mt-1 truncate text-[20px] font-extrabold tracking-[-0.02em] text-[#162846]">{pickup} <span className="px-1 font-normal text-[#4c73aa]">&#8594;</span> {delivery}</h1><p className="mt-1 text-[11px] text-[#74839a]">{dateLabel(load.pickupWindowStart)} <span className="px-2">&#8226;</span> {dateLabel(load.deliveryWindowEnd)} <span className="px-2">&#8226;</span> {distance} <span className="px-2">&#8226;</span> {text(load.transportType, 'Road')}</p></div><button type="button" aria-label="Close" onClick={onClose} className="ml-3 rounded p-1 text-[#71819a] hover:bg-[#f0f4f9] hover:text-[#1f4f91]"><X className="h-4 w-4" /></button></header>
    <nav className="flex shrink-0 gap-7 border-b border-[#e5ebf3] px-6 text-[11px] font-semibold text-[#6d7b91]"><span className="border-b-2 border-[#1769e8] py-2.5 text-[#1769e8]">{u('common.overview', 'Overview')}</span><span className="py-2.5">{u('postLoadModal.routeSummaryTitle', 'Route & Stops')}</span><span className="py-2.5">{u('tracking.attachedDocuments', 'Documents')}</span><span className="py-2.5">Company</span></nav>
    <main className="min-h-0 flex-1 overflow-y-auto p-3 sm:p-4"><div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_250px]"><section className="overflow-hidden rounded-[4px] border border-[#dfe7f1] bg-[#eef6f8]"><div className="relative h-[250px] sm:h-[335px]">{canRoute ? <MapContainer center={center!} zoom={5} scrollWheelZoom={false} dragging={false} zoomControl={false} className="h-full w-full"><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="&copy; OpenStreetMap" /><Polyline positions={[pickupPosition!, deliveryPosition!]} pathOptions={{ color: '#0879f9', weight: 4 }} /><Marker position={pickupPosition!} /><Marker position={deliveryPosition!} /></MapContainer> : <div className="flex h-full items-center justify-center text-xs text-[#71819a]">Route map unavailable</div>}<button type="button" disabled={!canRoute} onClick={() => setRouteOpen(true)} className="absolute bottom-3 left-3 z-[500] rounded-full border border-[#d8e3ee] bg-white px-3 py-1.5 text-[10px] font-bold text-[#3d5f91] shadow-sm disabled:opacity-50">&#8594; {u('postLoadModal.showRouteMap', 'Show Route Details')}</button></div></section>
      <section className="rounded-[4px] border border-[#dfe7f1] bg-white p-3"><h2 className="mb-3 text-[12px] font-extrabold text-[#1a2d4d]">{u('legacy.loadDetails.loadProfile', 'Load Overview')}</h2><div className="space-y-3 text-[10px]"><Info label="Equipment" value={text(load.truckType, 'Dry Van')} /><Info label="Weight" value={`${text(load.weight)} kg`} /><Info label="Distance" value={distance} /><Info label="Length" value={`${text(load.length)} m`} /><Info label="Commodity" value={text(load.goodsType, 'General goods')} /></div><div className="mt-5 border-t border-[#edf1f6] pt-3"><p className="text-[12px] font-extrabold">Stops (2)</p><Stop label="1. Pickup" place={pickup} tone="bg-[#16b878]" /><Stop label="2. Delivery" place={delivery} tone="bg-[#1769e8]" last /></div></section>
      </div>
      <div className="mt-3 grid grid-cols-2 gap-0 rounded-[4px] border border-[#dfe7f1] bg-white py-3 sm:grid-cols-5"><Metric icon={Truck} label="Equipment">{text(load.truckType, 'Dry Van')}</Metric><Metric icon={Package} label="Weight">{text(load.weight)} kg</Metric><Metric icon={MapPin} label="Distance">{distance}</Metric><Metric icon={Package} label="Commodity">{text(load.goodsType)}</Metric><Metric icon={Hash} label="Rate">{price}</Metric></div><div className="mt-3 rounded-[4px] border border-[#dfe7f1] bg-white p-3"><h2 className="mb-2 text-[12px] font-extrabold">Documents ({load.customsDocuments?.length || 0})</h2><CustomsDocumentList loadId={load.id} documents={load.customsDocuments} lang={lang} /></div></main></div><aside className="flex h-full w-[260px] shrink-0 flex-col overflow-y-auto border-l border-[#dfe7f1] bg-white p-3 [scrollbar-color:rgb(148_163_184/0.72)_transparent] [scrollbar-width:thin]"><p className="text-[10px] font-semibold text-[#75849b]">Rate</p><p className="text-[24px] font-extrabold text-[#162846]">{price}</p><p className="text-[10px] text-[#75849b]">Fixed rate</p><button type="button" onClick={() => void book()} disabled={booking} className="mt-4 h-9 w-full rounded-[4px] bg-[#0875f5] text-[11px] font-bold text-white shadow-sm hover:bg-[#0567da] disabled:opacity-60">{booking ? 'Booking...' : 'Book Load'}</button><button type="button" onClick={() => onEdit?.(load)} className="mt-2 h-9 w-full rounded-[4px] border border-[#cbd7e7] text-[11px] font-bold text-[#294a7c]">Edit Load</button><button type="button" onClick={() => onOperationsOpen?.(Number(load.shipmentOperationsId), load.id)} disabled={!load.shipmentOperationsId} className="mt-2 h-9 w-full rounded-[4px] border border-[#cbd7e7] text-[11px] font-bold text-[#294a7c] disabled:opacity-40">Open Operations</button><div className="mt-5 border-t border-[#edf1f6] pt-3"><p className="text-[10px] font-bold text-[#75849b]">Shipper</p><p className="mt-1 text-[12px] font-bold">{text(load.shipperName)}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-[#62738c]"><Phone className="h-3 w-3" />{text(load.contact?.phone, 'No phone')}</p></div></aside>{pickupPosition && deliveryPosition && <RouteMapModal open={routeOpen} onClose={() => setRouteOpen(false)} pickup={{ label: pickup, position: pickupPosition, kind: 'pickup' }} delivery={{ label: delivery, position: deliveryPosition, kind: 'delivery' }} lang={lang} />}</div>;
};