import { Package, Load, RouteLog } from './types';

export const MOCK_PACKAGES: Package[] = [
  {
    id: '1',
    trackingNumber: 'ER217960271BA',
    carrier: 'Parcel Force',
    status: 'In Transit',
    origin: 'London, UK',
    destination: 'Sarajevo, BA',
    addedDate: '28 February',
    transitDays: 1,
    currentLocation: [43.8563, 18.4131],
    history: [
      { date: '28 Feb, 10:00', status: 'In Transit', location: 'Sarajevo Hub' },
      { date: '27 Feb, 14:00', status: 'Processed', location: 'London Gateway' },
      { date: '26 Feb, 09:00', status: 'Picked Up', location: 'Sender Warehouse' },
    ]
  },
  {
    id: '2',
    trackingNumber: 'SWIFT-9921-X',
    carrier: 'CARGO.AI Express',
    status: 'Out for Delivery',
    origin: 'Berlin, DE',
    destination: 'Munich, DE',
    addedDate: '27 February',
    transitDays: 2,
    currentLocation: [48.1351, 11.5820],
    history: [
      { date: '28 Feb, 08:30', status: 'Out for Delivery', location: 'Munich Central' },
      { date: '27 Feb, 18:00', status: 'Arrived', location: 'Munich Hub' },
    ]
  }
];

export const MOCK_LOADS: Load[] = [
  {
    id: 'L1',
    title: 'Electronics Pallets',
    weight: '1200',
    price: 'EUR 450',
    pickup: 'Vienna, AT',
    delivery: 'Prague, CZ',
    date: 'March 2, 2026',
    author: 'TechLogistics GmbH',
    status: 'Available',
    cargoType: 'Electronics',
    goodsType: 'High Value',
    paymentTerms: 'Negotiable',
    eta: '2 March, 18:00'
  },
  {
    id: 'L2',
    title: 'Frozen Goods (Meat)',
    weight: '18000',
    price: 'EUR 2,100',
    pickup: 'Zagreb, HR',
    delivery: 'Berlin, DE',
    date: 'March 4, 2026',
    author: 'ColdChain Solutions',
    status: 'Assigned',
    cargoType: 'Perishable',
    goodsType: 'Fragile',
    paymentTerms: 'In Advance',
    eta: '4 March, 12:00'
  },
  {
    id: 'L3',
    title: 'Furniture Set',
    weight: '800',
    price: 'EUR 320',
    pickup: 'Sarajevo, BA',
    delivery: 'Banja Luka, BA',
    date: 'March 1, 2026',
    author: 'HomeStyle',
    status: 'Available',
    cargoType: 'Fragile',
    goodsType: 'Fragile',
    paymentTerms: 'Negotiable',
    eta: '1 March, 16:00'
  },
  {
    id: 'L4',
    title: 'Pharma Temperature Cargo',
    weight: '6200',
    price: 'EUR 1,480',
    pickup: 'Prague, CZ',
    delivery: 'Vienna, AT',
    date: 'March 5, 2026',
    author: 'MediChain',
    status: 'Assigned',
    cargoType: 'Perishable',
    goodsType: 'Flammable',
    paymentTerms: 'In Advance',
    eta: '5 March, 15:20'
  },
  {
    id: 'L5',
    title: 'Industrial Spare Parts',
    weight: '14000',
    price: 'EUR 1,950',
    pickup: 'Berlin, DE',
    delivery: 'Zagreb, HR',
    date: 'March 6, 2026',
    author: 'NordMach',
    status: 'Available',
    cargoType: 'Industrial',
    goodsType: 'Heavy',
    paymentTerms: 'On Delivery',
    eta: '6 March, 20:10'
  },
  {
    id: 'L6',
    title: 'Retail Mixed Pallets',
    weight: '4200',
    price: 'EUR 980',
    pickup: 'Banja Luka, BA',
    delivery: 'Sarajevo, BA',
    date: 'March 3, 2026',
    author: 'RetailFlow',
    status: 'Available',
    cargoType: 'General',
    goodsType: 'General',
    paymentTerms: 'Negotiable',
    eta: '3 March, 18:45'
  },
  {
    id: 'L7',
    title: 'Fresh Produce Batch',
    weight: '9700',
    price: 'EUR 1,260',
    pickup: 'Zagreb, HR',
    delivery: 'Vienna, AT',
    date: 'March 7, 2026',
    author: 'FreshWay',
    status: 'Assigned',
    cargoType: 'Perishable',
    goodsType: 'Perishable',
    paymentTerms: 'In Advance',
    eta: '7 March, 14:30'
  },
  {
    id: 'L8',
    title: 'Office Equipment Set',
    weight: '2800',
    price: 'EUR 740',
    pickup: 'Prague, CZ',
    delivery: 'Berlin, DE',
    date: 'March 8, 2026',
    author: 'OfficeTransit',
    status: 'Available',
    cargoType: 'Electronics',
    goodsType: 'Fragile',
    paymentTerms: 'Negotiable',
    eta: '8 March, 17:15'
  },
  {
    id: 'L9',
    title: 'Construction Tools',
    weight: '5100',
    price: 'EUR 1,020',
    pickup: 'Vienna, AT',
    delivery: 'Sarajevo, BA',
    date: 'March 9, 2026',
    author: 'BuildLink',
    status: 'Available',
    cargoType: 'Industrial',
    goodsType: 'Flammable',
    paymentTerms: 'On Delivery',
    eta: '9 March, 21:00'
  },
  {
    id: 'L10',
    title: 'Textile Rolls',
    weight: '3600',
    price: 'EUR 690',
    pickup: 'Berlin, DE',
    delivery: 'Prague, CZ',
    date: 'March 10, 2026',
    author: 'Textura GmbH',
    status: 'Assigned',
    cargoType: 'General',
    goodsType: 'General',
    paymentTerms: 'Negotiable',
    eta: '10 March, 13:40'
  },
  {
    id: 'L11',
    title: 'Auto Components',
    weight: '11200',
    price: 'EUR 1,720',
    pickup: 'Banja Luka, BA',
    delivery: 'Zagreb, HR',
    date: 'March 11, 2026',
    author: 'DriveCore',
    status: 'Available',
    cargoType: 'Automotive',
    goodsType: 'Heavy',
    paymentTerms: 'On Delivery',
    eta: '11 March, 12:25'
  },
  {
    id: 'L12',
    title: 'E-commerce Parcels',
    weight: '2100',
    price: 'EUR 560',
    pickup: 'Sarajevo, BA',
    delivery: 'Vienna, AT',
    date: 'March 12, 2026',
    author: 'QuickBox',
    status: 'Assigned',
    cargoType: 'General',
    goodsType: 'Fragile',
    paymentTerms: 'In Advance',
    eta: '12 March, 19:10'
  },
  {
    id: 'L13',
    title: 'High-Value Electronics',
    weight: '1600',
    price: 'EUR 1,340',
    pickup: 'Prague, CZ',
    delivery: 'Sarajevo, BA',
    date: 'March 13, 2026',
    author: 'SecureTech Freight',
    status: 'Available',
    cargoType: 'Electronics',
    goodsType: 'High Value',
    paymentTerms: 'Negotiable',
    eta: '13 March, 22:30'
  }
];

export const MOCK_ROUTES: RouteLog[] = [
  {
    id: 'R1',
    date: 'Feb 27, 2026',
    distance: '420 km',
    duration: '5h 30m',
    stops: 12,
    path: [[43.8563, 18.4131], [44.1997, 17.9048], [44.7722, 17.1910]]
  },
  {
    id: 'R2',
    date: 'Feb 26, 2026',
    distance: '150 km',
    duration: '2h 15m',
    stops: 5,
    path: [[43.8563, 18.4131], [43.7345, 18.2345], [43.6123, 18.1234]]
  }
];
